examen_project_new:
    path:     /new-exam/{id}
    defaults: { _controller: "MyAppJobOwnerBundle:Examen:new" }
    methods:  [GET, POST]

examen_new_ajax:
    path:     /new_examen
    defaults: { _controller: "MyAppJobOwnerBundle:Examen:exam" }
get_test:
    path:     /get_examen/{id}
    defaults: { _controller: "MyAppJobOwnerBundle:Examen:get" }
result_test:
    path:     /result_exam
    defaults: { _controller: "MyAppJobOwnerBundle:Examen:pass" }