freelancer_homepage:
    path:     /
    defaults: { _controller: FreelancerBundle:Default:index }
freelancer_home:
    path:     /
    defaults: { _controller: "FreelancerBundle:Freelancer:home" }
    methods:  DELETE

freelancer_admin_home:
    path:     /admin
    defaults: { _controller: MyAppAdminBundle:Admin:Admin }

freelancer_Freelancer:
    path:     /Freelancer
    defaults: { _controller: FreelancerBundle:Freelancer:Freelancer }

freelancer_JobOwner:
    path:     /JobOwner
    defaults: { _controller: MyAppJobOwnerBundle:JobOwner:jobOwner }

freelancer_alluser:
    path:     /Alluser
    defaults: { _controller: FreelancerBundle:Freelancer:Alluser }

freelancer_Showfreelancer:
    path:     /showfreelancer/{email}
    defaults: { _controller: FreelancerBundle:Freelancer:showfreelancer }

freelancer_Showjobowner:
    path:     /showjobowner/{email}
    defaults: { _controller: FreelancerBundle:Freelancer:showjobowner }

freelancer_EditProfile:
    path:     /Freelancer/Editprofile
    defaults: { _controller: FreelancerBundle:Freelancer:Editprofile }

freelancer_Reclamations:
    path:     /Reclamations
    defaults: { _controller: FreelancerBundle:Freelancer:Reclamations }

freelancer_CreateReclamations:
    path:     /CreateReclamations
    defaults: { _controller: FreelancerBundle:Freelancer:createreclamation }

freelancer_showreclamation:
    path:     /showreclamation/{id}
    defaults: { _controller: FreelancerBundle:Freelancer:showReclamation }

freelancer_Subscribe:
    path:     /Subscribe/{idsubscriber}
    defaults: { _controller: FreelancerBundle:Freelancer:Subscribe }

freelancer_UnSubscribe:
    path:     /UnSubscribe/{idsubscriber}
    defaults: { _controller: FreelancerBundle:Freelancer:UnSubscribe }
    defaults: { _controller: MyAppJobOwnerBundle:JobOwner:jobOwnerr }

mysubscriptions:
    path:     /mysubscriptions
    defaults: { _controller: FreelancerBundle:Subscription:mysubscriptions }


